global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus itself.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
  # MariaDB.
  - job_name: 'mariadb'
    static_configs:
      - targets: ['web:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['web:9113']

  - job_name: 'php-fpm'
    static_configs:
      - targets: ['web:9253']

  - job_name: 'redis'
    static_configs:
      - targets: ['web:9121']